#pragma once

#include "azer/base/image.h"
#include "azer/effect/effect.h"
#include "azer/effect/effect_creator.h"
#include "azer/effect/effect_params_adapter.h"
#include "azer/effect/effect_params_provider.h"
#include "azer/effect/light.h"
#include "azer/effect/material.h"
#include "azer/effect/overlay.h"
#include "azer/render/entity.h"
#include "azer/render/blending.h"
#include "azer/render/camera.h"
#include "azer/render/common.h"
#include "azer/render/mesh.h"
#include "azer/render/gpu_compute_task.h"
#include "azer/render/indices_buffer.h"
#include "azer/render/index_pack.h"
#include "azer/render/rasterizer_state.h"
#include "azer/render/render_target.h"
#include "azer/render/render_system.h"
#include "azer/render/renderer.h"
#include "azer/render/shader_param_table.h"
#include "azer/render/structured_buffer.h"
#include "azer/render/technique.h"
#include "azer/render/texture_view.h"
#include "azer/render/vertex_buffer.h"
#include "azer/render/vertex_pack.h"

#include "azer/render/scoped_render_target.h"
#include "azer/render/render_system_loader.h"

