 /**
 * Generated by afx
 * dont edit by hande
 */
#include <stddef.h>

#include "base/basictypes.h"
#include "base/logging.h"

#include "azer/render/render.h"

const azer::VertexDesc::Desc HaredwareSkinnedMeshEffect::kVertexDesc[] = {
  {"POSITION", 0, azer::kVec4},
  {"COORDTEX", 0, azer::kVec2},
  {"NORMAL", 0, azer::kVec4},
  {"INDEX", 0, azer::kIntVec4},
  {"WEIGHTS", 0, azer::kVec4},
};

const int HaredwareSkinnedMeshEffect::kVertexDescNum = arraysize(HaredwareSkinnedMeshEffect::kVertexDesc);

HaredwareSkinnedMeshEffect::HaredwareSkinnedMeshEffect(const std::vector<std::string>& sources, azer::RenderSystem* rs) 
  : azer::Effect(rs) 
  , sources_(sources) {
  DCHECK(sources.size() == azer::kRenderPipelineStageNum);
  DCHECK(!sources[azer::kVertexStage].empty());
  DCHECK(!sources[azer::kPixelStage].empty());
  Init();
}

HaredwareSkinnedMeshEffect::~HaredwareSkinnedMeshEffect() {
}

void HaredwareSkinnedMeshEffect::Init() {
  InitTechnique();
  // generate GpuTable init for stage azer::kVertexStage
  azer::GpuConstantsTable::Desc vs_table_desc[] = {
    azer::GpuConstantsTable::Desc("bone", azer::GpuConstantsType::kMatrix4,
         offsetof(vs_cbuffer,bone), 100),
    azer::GpuConstantsTable::Desc("world", azer::GpuConstantsType::kMatrix4,
         offsetof(vs_cbuffer,world), 1),
    azer::GpuConstantsTable::Desc("pv", azer::GpuConstantsType::kMatrix4,
         offsetof(vs_cbuffer,pv), 1),
  };
  gpu_table_[azer::kVertexStage].reset(render_system_->CreateGpuConstantsTable(
      arraysize(vs_table_desc), vs_table_desc));
}

void HaredwareSkinnedMeshEffect::InitTechnique() {
  technique_.reset(render_system_->CreateTechnique());
  vertex_desc_ptr_.reset(new azer::VertexDesc(kVertexDesc, kVertexDescNum));
  const std::string& vs_shader_source = sources_[azer::kVertexStage];
  DCHECK(!vs_shader_source.empty());
  azer::GpuProgramPtr vs_gpup_ptr(render_system_->CreateVertexGpuProgram(
      vertex_desc_ptr_, vs_shader_source));
  DCHECK(vs_gpup_ptr.get() != NULL);
  technique_->AddGpuProgram(vs_gpup_ptr);
  {
    const std::string& source = sources_[azer::kPixelStage];
    DCHECK(!source.empty());
    azer::GpuProgramPtr gpup_ptr(render_system_->CreateGpuProgram(
        azer::kPixelStage, source));
    DCHECK(gpup_ptr.get() != NULL);
    technique_->AddGpuProgram(gpup_ptr);
  }
  technique_->Use(render_system_->GetDefaultRenderer());
}

void HaredwareSkinnedMeshEffect::UseTexture(azer::Renderer* renderer) {
  renderer->UseTexture(azer::kPixelStage, 0, ps_tex_.get());
}
void HaredwareSkinnedMeshEffect::SetMaterial(azer::MaterialPtr material) {
}


