 /**
 * Generated by afx
 * dont edit by hande
 */
#include "azer/render/render.h"
#include "azer/math/math.h"


class effect: public azer::Effect {
 public:
  effect(const std::vector<std::string>& sources, azer::RenderSystem* rs);
  ~effect();
 /**
   * uniform buffer
   */
  #pragma pack(push, 4)
  struct ps_cbuffer {
    azer::Light light1;
    azer::Material::material mtrl;
  };
  #pragma pack(pop)

  void SetLight(const azer::Light& value) {
    azer::GpuConstantsTable* tb = gpu_table_[(int)azer::kPixelStage].get();
    DCHECK(tb != NULL);
    tb->SetValue(0, &value, sizeof(azer::Light));
  }
  void set_ps_mtrl(const azer::Material::material& value) {
    azer::GpuConstantsTable* tb = gpu_table_[(int)azer::kPixelStage].get();
    DCHECK(tb != NULL);
    tb->SetValue(1, &value, sizeof(azer::Material::material));
  }
  void set_ps_mtrl__difftex_(int index, const azer::TexturePtr& texture) {
    DCHECK_LT(index, (int)arraysize(ps_mtrl__difftex_));
    ps_mtrl__difftex_[index] = texture;
  }


  /**
  * struct of Vertex 
  * input of Vertex Shader
  */
  struct Vertex {
    azer::Vector3 position;
    azer::Vector3 normal;
    azer::Vector3 texcoord;
    Vertex(const azer::Vector3 p0, const azer::Vector3 p1, const azer::Vector3 p2)
      : position(p0)
      , normal(p1)
      , texcoord(p2)
      {}
  };

  azer::VertexDescPtr GetVertexDesc() { return vertex_desc_ptr_;}
  static const int kVertexDescNum;
  static const azer::VertexDesc::Desc kVertexDesc[];
 protected:
  void Init();
  void InitTechnique();
  virtual void UseTexture(azer::Renderer* renderer) OVERRIDE;
  virtual void SetMaterial(azer::MaterialPtr material) OVERRIDE;
  const std::vector<std::string>& sources_;

  azer::TexturePtr ps_mtrl__difftex_[3];

  azer::VertexDescPtr vertex_desc_ptr_;
  DISALLOW_COPY_AND_ASSIGN(effect);
};
