#pragma once

#include "azer/render/axis_aligned_box.h"
#include "azer/render/camera.h"
#include "azer/render/effect.h"
#include "azer/render/effect/shadow_map.h"
#include "azer/render/gpu_constants_table.h"
#include "azer/render/light.h"
#include "azer/render/material.h"
#include "azer/render/render_system_enum.h"
#include "azer/render/render_target.h"
#include "azer/render/render_system.h"
#include "azer/render/renderer.h"
#include "azer/render/overlay.h"
#include "azer/render/technique.h"
#include "azer/render/vertex_data.h"
#include "azer/ui/window/window_host.h"

#include "azer/render/scoped_render_target.h"
#include "azer/render/util/coordinate_grid.h"
#include "azer/render/util/render_system_loader.h"
#include "azer/render/util/shader_array.h"
