#pragma once

#include "azer/math/math.h"
#include "azer/render/util/coordinate_grid.h"
#include "azer/render/util/effects/diffuse_effect.h"
#include "azer/render/util/effects/pvw_effect.h"
#include "azer/render/util/effects/vertex_desc.h"
#include "azer/render/util/geometry/box_object.h"
#include "azer/render/util/geometry/cone_object.h"
#include "azer/render/util/geometry/cylinder_object.h"
#include "azer/render/util/geometry/sphere_object.h"
#include "azer/render/util/light.h"
#include "azer/render/util/shader_util.h"
#include "azer/render/util/tile.h"
#include "azer/render/util/vertex_pack.h"
